// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/node.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiNodeInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 383260810;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'lattice_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiNodeNodeConnect({required Node that, required String ticket});

  Stream<LatticeEvent> crateApiNodeNodeEvents({required Node that});

  String crateApiNodeNodeFingerprint({required Node that});

  String crateApiNodeNodeMnemonic({required Node that});

  Future<String> crateApiNodeNodeMyTicket({required Node that});

  Future<Node> crateApiNodeNodeOpen({
    required String dir,
    required String passphrase,
  });

  String crateApiNodeNodePeerIdHex({required Node that});

  Future<void> crateApiNodeNodeSend({
    required Node that,
    required String peerIdHex,
    required String body,
  });

  void crateApiNodeNodeStartListening({required Node that});

  void crateApiNodeNodeStopListening({required Node that});

  Future<NewIdentity> crateApiNodeGenerateIdentity();

  bool crateApiNodeIdentityExists({required String dir});

  Future<void> crateApiNodeInitApp();

  Future<IdentitySummary> crateApiNodeStoreIdentity({
    required String dir,
    required String mnemonic,
    required String passphrase,
  });

  Future<IdentitySummary> crateApiNodeSummarizeMnemonic({
    required String mnemonic,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Node;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Node;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_NodePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiNodeNodeConnect({required Node that, required String ticket}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
            that,
            serializer,
          );
          sse_encode_String(ticket, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNodeNodeConnectConstMeta,
        argValues: [that, ticket],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeNodeConnectConstMeta => const TaskConstMeta(
    debugName: "Node_connect",
    argNames: ["that", "ticket"],
  );

  @override
  Stream<LatticeEvent> crateApiNodeNodeEvents({required Node that}) {
    final sink = RustStreamSink<LatticeEvent>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
            that,
            serializer,
          );
          sse_encode_StreamSink_lattice_event_Sse(sink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNodeNodeEventsConstMeta,
        argValues: [that, sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiNodeNodeEventsConstMeta =>
      const TaskConstMeta(debugName: "Node_events", argNames: ["that", "sink"]);

  @override
  String crateApiNodeNodeFingerprint({required Node that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNodeNodeFingerprintConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeNodeFingerprintConstMeta =>
      const TaskConstMeta(debugName: "Node_fingerprint", argNames: ["that"]);

  @override
  String crateApiNodeNodeMnemonic({required Node that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNodeNodeMnemonicConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeNodeMnemonicConstMeta =>
      const TaskConstMeta(debugName: "Node_mnemonic", argNames: ["that"]);

  @override
  Future<String> crateApiNodeNodeMyTicket({required Node that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNodeNodeMyTicketConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeNodeMyTicketConstMeta =>
      const TaskConstMeta(debugName: "Node_my_ticket", argNames: ["that"]);

  @override
  Future<Node> crateApiNodeNodeOpen({
    required String dir,
    required String passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNodeNodeOpenConstMeta,
        argValues: [dir, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeNodeOpenConstMeta => const TaskConstMeta(
    debugName: "Node_open",
    argNames: ["dir", "passphrase"],
  );

  @override
  String crateApiNodeNodePeerIdHex({required Node that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNodeNodePeerIdHexConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeNodePeerIdHexConstMeta =>
      const TaskConstMeta(debugName: "Node_peer_id_hex", argNames: ["that"]);

  @override
  Future<void> crateApiNodeNodeSend({
    required Node that,
    required String peerIdHex,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
            that,
            serializer,
          );
          sse_encode_String(peerIdHex, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNodeNodeSendConstMeta,
        argValues: [that, peerIdHex, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeNodeSendConstMeta => const TaskConstMeta(
    debugName: "Node_send",
    argNames: ["that", "peerIdHex", "body"],
  );

  @override
  void crateApiNodeNodeStartListening({required Node that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNodeNodeStartListeningConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeNodeStartListeningConstMeta =>
      const TaskConstMeta(
        debugName: "Node_start_listening",
        argNames: ["that"],
      );

  @override
  void crateApiNodeNodeStopListening({required Node that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNodeNodeStopListeningConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeNodeStopListeningConstMeta =>
      const TaskConstMeta(debugName: "Node_stop_listening", argNames: ["that"]);

  @override
  Future<NewIdentity> crateApiNodeGenerateIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_new_identity,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNodeGenerateIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeGenerateIdentityConstMeta =>
      const TaskConstMeta(debugName: "generate_identity", argNames: []);

  @override
  bool crateApiNodeIdentityExists({required String dir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNodeIdentityExistsConstMeta,
        argValues: [dir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeIdentityExistsConstMeta =>
      const TaskConstMeta(debugName: "identity_exists", argNames: ["dir"]);

  @override
  Future<void> crateApiNodeInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNodeInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<IdentitySummary> crateApiNodeStoreIdentity({
    required String dir,
    required String mnemonic,
    required String passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNodeStoreIdentityConstMeta,
        argValues: [dir, mnemonic, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeStoreIdentityConstMeta => const TaskConstMeta(
    debugName: "store_identity",
    argNames: ["dir", "mnemonic", "passphrase"],
  );

  @override
  Future<IdentitySummary> crateApiNodeSummarizeMnemonic({
    required String mnemonic,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNodeSummarizeMnemonicConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNodeSummarizeMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "summarize_mnemonic",
        argNames: ["mnemonic"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Node => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Node => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Node
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NodeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Node
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NodeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Node
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NodeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<LatticeEvent> dco_decode_StreamSink_lattice_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  IdentitySummary dco_decode_identity_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IdentitySummary(
      peerIdHex: dco_decode_String(arr[0]),
      fingerprint: dco_decode_String(arr[1]),
    );
  }

  @protected
  LatticeEvent dco_decode_lattice_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return LatticeEvent_Listening(ticket: dco_decode_String(raw[1]));
      case 1:
        return LatticeEvent_ListeningStopped();
      case 2:
        return LatticeEvent_PeerConnected(peerIdHex: dco_decode_String(raw[1]));
      case 3:
        return LatticeEvent_Resumed(peerIdHex: dco_decode_String(raw[1]));
      case 4:
        return LatticeEvent_Reconnecting(peerIdHex: dco_decode_String(raw[1]));
      case 5:
        return LatticeEvent_Link(
          peerIdHex: dco_decode_String(raw[1]),
          direct: dco_decode_bool(raw[2]),
          rttMs: dco_decode_opt_box_autoadd_u_32(raw[3]),
        );
      case 6:
        return LatticeEvent_Message(
          peerIdHex: dco_decode_String(raw[1]),
          body: dco_decode_String(raw[2]),
        );
      case 7:
        return LatticeEvent_PeerDisconnected(
          peerIdHex: dco_decode_String(raw[1]),
        );
      case 8:
        return LatticeEvent_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  NewIdentity dco_decode_new_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NewIdentity(
      mnemonic: dco_decode_String(arr[0]),
      peerIdHex: dco_decode_String(arr[1]),
      fingerprint: dco_decode_String(arr[2]),
    );
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Node
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NodeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Node
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NodeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Node
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NodeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<LatticeEvent> sse_decode_StreamSink_lattice_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  IdentitySummary sse_decode_identity_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerIdHex = sse_decode_String(deserializer);
    var var_fingerprint = sse_decode_String(deserializer);
    return IdentitySummary(
      peerIdHex: var_peerIdHex,
      fingerprint: var_fingerprint,
    );
  }

  @protected
  LatticeEvent sse_decode_lattice_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_ticket = sse_decode_String(deserializer);
        return LatticeEvent_Listening(ticket: var_ticket);
      case 1:
        return LatticeEvent_ListeningStopped();
      case 2:
        var var_peerIdHex = sse_decode_String(deserializer);
        return LatticeEvent_PeerConnected(peerIdHex: var_peerIdHex);
      case 3:
        var var_peerIdHex = sse_decode_String(deserializer);
        return LatticeEvent_Resumed(peerIdHex: var_peerIdHex);
      case 4:
        var var_peerIdHex = sse_decode_String(deserializer);
        return LatticeEvent_Reconnecting(peerIdHex: var_peerIdHex);
      case 5:
        var var_peerIdHex = sse_decode_String(deserializer);
        var var_direct = sse_decode_bool(deserializer);
        var var_rttMs = sse_decode_opt_box_autoadd_u_32(deserializer);
        return LatticeEvent_Link(
          peerIdHex: var_peerIdHex,
          direct: var_direct,
          rttMs: var_rttMs,
        );
      case 6:
        var var_peerIdHex = sse_decode_String(deserializer);
        var var_body = sse_decode_String(deserializer);
        return LatticeEvent_Message(peerIdHex: var_peerIdHex, body: var_body);
      case 7:
        var var_peerIdHex = sse_decode_String(deserializer);
        return LatticeEvent_PeerDisconnected(peerIdHex: var_peerIdHex);
      case 8:
        var var_message = sse_decode_String(deserializer);
        return LatticeEvent_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  NewIdentity sse_decode_new_identity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mnemonic = sse_decode_String(deserializer);
    var var_peerIdHex = sse_decode_String(deserializer);
    var var_fingerprint = sse_decode_String(deserializer);
    return NewIdentity(
      mnemonic: var_mnemonic,
      peerIdHex: var_peerIdHex,
      fingerprint: var_fingerprint,
    );
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
    Node self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NodeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
    Node self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NodeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNode(
    Node self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NodeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_lattice_event_Sse(
    RustStreamSink<LatticeEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_lattice_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_identity_summary(
    IdentitySummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerIdHex, serializer);
    sse_encode_String(self.fingerprint, serializer);
  }

  @protected
  void sse_encode_lattice_event(LatticeEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case LatticeEvent_Listening(ticket: final ticket):
        sse_encode_i_32(0, serializer);
        sse_encode_String(ticket, serializer);
      case LatticeEvent_ListeningStopped():
        sse_encode_i_32(1, serializer);
      case LatticeEvent_PeerConnected(peerIdHex: final peerIdHex):
        sse_encode_i_32(2, serializer);
        sse_encode_String(peerIdHex, serializer);
      case LatticeEvent_Resumed(peerIdHex: final peerIdHex):
        sse_encode_i_32(3, serializer);
        sse_encode_String(peerIdHex, serializer);
      case LatticeEvent_Reconnecting(peerIdHex: final peerIdHex):
        sse_encode_i_32(4, serializer);
        sse_encode_String(peerIdHex, serializer);
      case LatticeEvent_Link(
        peerIdHex: final peerIdHex,
        direct: final direct,
        rttMs: final rttMs,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(peerIdHex, serializer);
        sse_encode_bool(direct, serializer);
        sse_encode_opt_box_autoadd_u_32(rttMs, serializer);
      case LatticeEvent_Message(peerIdHex: final peerIdHex, body: final body):
        sse_encode_i_32(6, serializer);
        sse_encode_String(peerIdHex, serializer);
        sse_encode_String(body, serializer);
      case LatticeEvent_PeerDisconnected(peerIdHex: final peerIdHex):
        sse_encode_i_32(7, serializer);
        sse_encode_String(peerIdHex, serializer);
      case LatticeEvent_Error(message: final message):
        sse_encode_i_32(8, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_new_identity(NewIdentity self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mnemonic, serializer);
    sse_encode_String(self.peerIdHex, serializer);
    sse_encode_String(self.fingerprint, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class NodeImpl extends RustOpaque implements Node {
  // Not to be used by end users
  NodeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NodeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Node,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Node,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_NodePtr,
  );

  /// Dial a peer by ticket (runs in the background; watch the event stream).
  void connect({required String ticket}) =>
      RustLib.instance.api.crateApiNodeNodeConnect(that: this, ticket: ticket);

  /// Subscribe to the node's event stream. Spawns a forwarder on the runtime
  /// that pushes each event into Dart until the node is torn down.
  Stream<LatticeEvent> events() =>
      RustLib.instance.api.crateApiNodeNodeEvents(that: this);

  /// Short, comparable fingerprint of the PeerId.
  String fingerprint() =>
      RustLib.instance.api.crateApiNodeNodeFingerprint(that: this);

  /// The 24-word backup mnemonic — gate behind biometric + explicit intent.
  String mnemonic() =>
      RustLib.instance.api.crateApiNodeNodeMnemonic(that: this);

  /// The dial ticket for this node (binds the transport if needed). Render as QR.
  Future<String> myTicket() =>
      RustLib.instance.api.crateApiNodeNodeMyTicket(that: this);

  /// This node's stable PeerId, hex-encoded.
  String peerIdHex() =>
      RustLib.instance.api.crateApiNodeNodePeerIdHex(that: this);

  /// Send a UTF-8 message to a connected peer (by hex PeerId).
  Future<void> send({required String peerIdHex, required String body}) =>
      RustLib.instance.api.crateApiNodeNodeSend(
        that: this,
        peerIdHex: peerIdHex,
        body: body,
      );

  /// Go online + accept connections; emits a `Listening` event with the ticket.
  void startListening() =>
      RustLib.instance.api.crateApiNodeNodeStartListening(that: this);

  /// Stop accepting new connections; emits `ListeningStopped`.
  void stopListening() =>
      RustLib.instance.api.crateApiNodeNodeStopListening(that: this);
}
