// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'node.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `blocking`, `on_rt`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`

/// Generate a brand-new PQ-hybrid identity (not yet persisted).
Future<NewIdentity> generateIdentity() =>
    RustLib.instance.api.crateApiNodeGenerateIdentity();

/// Validate a mnemonic and preview its identity (recovery / confirmation).
Future<IdentitySummary> summarizeMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiNodeSummarizeMnemonic(mnemonic: mnemonic);

/// Encrypt + persist `mnemonic` under `passphrase` to `<dir>/identity.age`.
Future<IdentitySummary> storeIdentity({
  required String dir,
  required String mnemonic,
  required String passphrase,
}) => RustLib.instance.api.crateApiNodeStoreIdentity(
  dir: dir,
  mnemonic: mnemonic,
  passphrase: passphrase,
);

/// Whether an encrypted identity already exists at `dir`.
bool identityExists({required String dir}) =>
    RustLib.instance.api.crateApiNodeIdentityExists(dir: dir);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Node>>
abstract class Node implements RustOpaqueInterface {
  /// Dial a peer by ticket (runs in the background; watch the event stream).
  void connect({required String ticket});

  /// Subscribe to the node's event stream. Spawns a forwarder on the runtime
  /// that pushes each event into Dart until the node is torn down.
  Stream<LatticeEvent> events();

  /// Short, comparable fingerprint of the PeerId.
  String fingerprint();

  /// The 24-word backup mnemonic — gate behind biometric + explicit intent.
  String mnemonic();

  /// The dial ticket for this node (binds the transport if needed). Render as QR.
  Future<String> myTicket();

  /// Unlock: decrypt the stored identity in `dir` with `passphrase` and build
  /// a node. Network binds lazily on `startListening`/`connect`.
  static Future<Node> open({required String dir, required String passphrase}) =>
      RustLib.instance.api.crateApiNodeNodeOpen(
        dir: dir,
        passphrase: passphrase,
      );

  /// This node's stable PeerId, hex-encoded.
  String peerIdHex();

  /// Send a UTF-8 message to a connected peer (by hex PeerId).
  Future<void> send({required String peerIdHex, required String body});

  /// Go online + accept connections; emits a `Listening` event with the ticket.
  void startListening();

  /// Stop accepting new connections; emits `ListeningStopped`.
  void stopListening();
}

/// Public, non-secret summary of an identity.
class IdentitySummary {
  final String peerIdHex;
  final String fingerprint;

  const IdentitySummary({required this.peerIdHex, required this.fingerprint});

  @override
  int get hashCode => peerIdHex.hashCode ^ fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentitySummary &&
          runtimeType == other.runtimeType &&
          peerIdHex == other.peerIdHex &&
          fingerprint == other.fingerprint;
}

@freezed
sealed class LatticeEvent with _$LatticeEvent {
  const LatticeEvent._();

  const factory LatticeEvent.listening({required String ticket}) =
      LatticeEvent_Listening;
  const factory LatticeEvent.listeningStopped() = LatticeEvent_ListeningStopped;
  const factory LatticeEvent.peerConnected({required String peerIdHex}) =
      LatticeEvent_PeerConnected;
  const factory LatticeEvent.resumed({required String peerIdHex}) =
      LatticeEvent_Resumed;
  const factory LatticeEvent.reconnecting({required String peerIdHex}) =
      LatticeEvent_Reconnecting;
  const factory LatticeEvent.message({
    required String peerIdHex,
    required String body,
  }) = LatticeEvent_Message;
  const factory LatticeEvent.peerDisconnected({required String peerIdHex}) =
      LatticeEvent_PeerDisconnected;
  const factory LatticeEvent.error({required String message}) =
      LatticeEvent_Error;
}

/// A freshly generated identity — mnemonic shown once, then stored.
class NewIdentity {
  final String mnemonic;
  final String peerIdHex;
  final String fingerprint;

  const NewIdentity({
    required this.mnemonic,
    required this.peerIdHex,
    required this.fingerprint,
  });

  @override
  int get hashCode =>
      mnemonic.hashCode ^ peerIdHex.hashCode ^ fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewIdentity &&
          runtimeType == other.runtimeType &&
          mnemonic == other.mnemonic &&
          peerIdHex == other.peerIdHex &&
          fingerprint == other.fingerprint;
}
